// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import loadEnv from "./src/config/env";
loadEnv();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'npx ts-node prisma/seed.ts',
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
