export enum PropertyStep {
  TYPE = "type",
  LOCATION = "location",
  DETAILS = "details",
  FACILITIES = "facilities",
  NEARBY = "nearby",
  MARINE_LIFE = "marine-life",
  HOUSE_RULES = "house-rules",
  LANGUAGES = "languages",
  HOST_PROFILE = "host-profile",
  POLICIES = "policies",
  UNITS = "units",
  IMAGES = "images",
  PRICING = "pricing",
  RATE_PLANS = "rate-plans",
  LISTING_STATUS = "listing-status",
  FINAL = "final",
}
